### PR TITLE
Fix issue with webpack_public_path and cdns

### LINKED ISSUE #57: Fix issue with webpack_public_path and cdns
We were using `path.join` on the webpack public path causing problems
when using cdns due to double slashes being transformed into single slashes.

### PR DESCRIPTION
**Pull request by ganemone**
Fixes #57

### CODE REVIEW

File: src/server.js [hunk 1]
```diff
@@ -130,8 +130,13 @@ function getCoreGlobals(ctx) {
 
 function getUrls({chunkUrlMap, webpackPublicPath}, chunks) {
   return chunks.map(id => {
-    const url = chunkUrlMap.get(id).get('es5');
-    return {id, url: path.join(webpackPublicPath, url)};
+    let url = chunkUrlMap.get(id).get('es5');
+    if (webpackPublicPath[webpackPublicPath.length - 1] === '/') {
```
Comment (KevinGrandon) [inline src/server.js]: Maybe https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith ?

**Comment by ganemone** [comment]
!merge
